const canvas=document.getElementById('game'),ctx=canvas.getContext('2d'); const scoreEl=document.getElementById('score'),bestEl=document.getElementById('best'); const restartBtn=document.getElementById('restart');
const grid=24, size=20; let snake, dir, nextDir, apple, score, best=+localStorage.getItem('tiny-snake-best')||0, over, last=0, speed=130; bestEl.textContent=best;
function rndCell(){return {x:Math.floor(Math.random()*grid),y:Math.floor(Math.random()*grid)}}
function placeApple(){do apple=rndCell(); while(snake.some(s=>s.x===apple.x&&s.y===apple.y))}
function reset(){snake=[{x:8,y:12},{x:7,y:12},{x:6,y:12}]; dir={x:1,y:0}; nextDir={x:1,y:0}; score=0; over=false; speed=130; scoreEl.textContent=0; placeApple();}
function update(){ if(over) return; dir=nextDir; const head={x:snake[0].x+dir.x,y:snake[0].y+dir.y}; if(head.x<0||head.y<0||head.x>=grid||head.y>=grid||snake.some(s=>s.x===head.x&&s.y===head.y)){over=true; return;} snake.unshift(head); if(head.x===apple.x&&head.y===apple.y){score++; scoreEl.textContent=score; if(score>best){best=score; localStorage.setItem('tiny-snake-best',best); bestEl.textContent=best;} if(speed>70) speed-=3; placeApple();} else snake.pop();}
function draw(){ ctx.fillStyle='#eef9d8'; ctx.fillRect(0,0,480,480); for(let y=0;y<grid;y++) for(let x=0;x<grid;x++){ctx.fillStyle=(x+y)%2===0?'#dff0be':'#d2e7aa'; ctx.fillRect(x*size,y*size,size,size);} ctx.fillStyle='#d64545'; ctx.fillRect(apple.x*size+2,apple.y*size+2,16,16); ctx.fillStyle='#2f7d32'; ctx.fillRect(apple.x*size+8,apple.y*size,4,6); snake.forEach((s,i)=>{ctx.fillStyle=i===0?'#355e3b':'#4f8f32'; ctx.fillRect(s.x*size+1,s.y*size+1,18,18);}); if(over){ctx.fillStyle='rgba(255,249,232,.94)';ctx.fillRect(95,190,290,100);ctx.strokeStyle='#2f2a24';ctx.lineWidth=4;ctx.strokeRect(95,190,290,100);ctx.fillStyle='#2c2a26';ctx.textAlign='center';ctx.font='bold 24px monospace';ctx.fillText('SNAKE DOWN',240,225);ctx.font='16px monospace';ctx.fillText('Press Restart to play again',240,252);}}
function tick(ts){if(ts-last>speed){last=ts; update()} draw(); requestAnimationFrame(tick)}
window.addEventListener('keydown',e=>{const k=e.key.toLowerCase(); if((k==='arrowup'||k==='w')&&dir.y!==1) nextDir={x:0,y:-1}; if((k==='arrowdown'||k==='s')&&dir.y!==-1) nextDir={x:0,y:1}; if((k==='arrowleft'||k==='a')&&dir.x!==1) nextDir={x:-1,y:0}; if((k==='arrowright'||k==='d')&&dir.x!==-1) nextDir={x:1,y:0};}); restartBtn.onclick=reset; reset(); requestAnimationFrame(tick);
