const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
const scoreEl=document.getElementById('score'),bestEl=document.getElementById('best');
const restartBtn=document.getElementById('restart');
let best=+localStorage.getItem('flappy-birb-best')||0;bestEl.textContent=best;
const state={bird:null,pipes:[],score:0,started:false,over:false,spawn:0,bgOffset:0};
function reset(){state.bird={x:110,y:280,vy:0,size:18};state.pipes=[];state.score=0;state.started=false;state.over=false;state.spawn=0;scoreEl.textContent=0;}
function flap(){if(state.over) reset(); state.started=true; state.bird.vy=-6.8;}
function pipePair(){const gap=150;const top=Math.random()*250+80;state.pipes.push({x:canvas.width+40,top,gap,passed:false});}
function drawPixelBird(b){ctx.fillStyle='#f2c230';ctx.fillRect(b.x,b.y,b.size,b.size);ctx.fillStyle='#fff';ctx.fillRect(b.x+10,b.y+4,6,6);ctx.fillStyle='#000';ctx.fillRect(b.x+13,b.y+6,2,2);ctx.fillStyle='#e36b2c';ctx.fillRect(b.x+16,b.y+8,8,4);ctx.fillStyle='#8c5a12';ctx.fillRect(b.x-2,b.y+5,4,8);}
function cloud(x,y,s){ctx.fillStyle='rgba(255,255,255,.85)';ctx.fillRect(x,y,s*2,s);ctx.fillRect(x+s*0.5,y-s*0.5,s*2,s);ctx.fillRect(x+s,y,s*2,s);}
function hill(x,y,w,h,c){ctx.fillStyle=c;ctx.beginPath();ctx.moveTo(x,y);ctx.quadraticCurveTo(x+w*.5,y-h,x+w,y);ctx.fill();}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#9dd6ff';ctx.fillRect(0,0,canvas.width,canvas.height); cloud(60-state.bgOffset*0.2,90,18); cloud(240-state.bgOffset*0.15,140,16); cloud(390-state.bgOffset*0.25,70,14); hill(-40-state.bgOffset,560,240,70,'#82c95e'); hill(120-state.bgOffset,560,260,95,'#74b952'); hill(330-state.bgOffset,560,220,80,'#8fd266'); ctx.fillStyle='#d6c27b';ctx.fillRect(0,590,canvas.width,50); for(const p of state.pipes){ctx.fillStyle='#4f8f32';ctx.fillRect(p.x,0,44,p.top);ctx.fillRect(p.x,p.top+p.gap,44,canvas.height-(p.top+p.gap));ctx.fillStyle='#78b84d';ctx.fillRect(p.x-4,p.top-16,52,16);ctx.fillRect(p.x-4,p.top+p.gap,52,16);} drawPixelBird(state.bird); if(!state.started&&!state.over){ctx.fillStyle='rgba(44,42,38,.9)';ctx.font='bold 20px monospace';ctx.textAlign='center';ctx.fillText('PRESS SPACE TO START',canvas.width/2,310);} if(state.over){ctx.fillStyle='rgba(255,249,232,.92)';ctx.fillRect(100,220,280,120);ctx.strokeStyle='#2f2a24';ctx.lineWidth=4;ctx.strokeRect(100,220,280,120);ctx.fillStyle='#2c2a26';ctx.font='bold 24px monospace';ctx.textAlign='center';ctx.fillText('GAME OVER',240,265);ctx.font='16px monospace';ctx.fillText('Press Space or Restart',240,300);}}
function update(){ if(state.over) return; if(state.started){ state.bgOffset=(state.bgOffset+1.5)%canvas.width; state.bird.vy+=0.34; state.bird.y+=state.bird.vy; state.spawn++; if(state.spawn>95){pipePair(); state.spawn=0;} for(const p of state.pipes){p.x-=2.7; if(!p.passed && p.x+44<state.bird.x){p.passed=true; state.score++; scoreEl.textContent=state.score; if(state.score>best){best=state.score; localStorage.setItem('flappy-birb-best',best); bestEl.textContent=best;}} const hitX=state.bird.x+state.bird.size>p.x && state.bird.x<p.x+44; const hitY=state.bird.y<p.top || state.bird.y+state.bird.size>p.top+p.gap; if(hitX&&hitY) state.over=true;} state.pipes=state.pipes.filter(p=>p.x>-60); if(state.bird.y<0 || state.bird.y+state.bird.size>590) state.over=true;} else {state.bgOffset=(state.bgOffset+0.4)%canvas.width; state.bird.y+=Math.sin(Date.now()/150)*0.35;}}
function loop(){update();draw();requestAnimationFrame(loop)}
window.addEventListener('keydown',e=>{if([' ','w','ArrowUp'].includes(e.key)) {e.preventDefault(); flap();}}); canvas.addEventListener('pointerdown',flap); restartBtn.onclick=reset; reset(); loop();
