const canvas=document.getElementById('game'),ctx=canvas.getContext('2d'); const scoreEl=document.getElementById('score'),bestEl=document.getElementById('best'),restartBtn=document.getElementById('restart');
let best=+localStorage.getItem('dash-runner-best')||0; bestEl.textContent=best; let player, obstacles, distance, speed, gameOver, spawn;
function reset(){player={x:80,y:250,w:28,h:36,vy:0,onGround:true}; obstacles=[]; distance=0; speed=5; gameOver=false; spawn=0; scoreEl.textContent=0;}
function jump(){if(player.onGround&&!gameOver){player.vy=-12; player.onGround=false;} else if(gameOver) reset();}
function update(){ if(gameOver) return; distance++; if(distance%240===0) speed+=0.25; scoreEl.textContent=Math.floor(distance/10); spawn++; if(spawn>Math.max(42,95-speed*6)){spawn=0; const tall=Math.random()>0.55; obstacles.push({x:canvas.width+20,y:tall?228:246,w:tall?24:18,h:tall?60:42});} player.vy+=0.6; player.y+=player.vy; if(player.y>=250){player.y=250; player.vy=0; player.onGround=true;} obstacles.forEach(o=>o.x-=speed); obstacles=obstacles.filter(o=>o.x>-40); for(const o of obstacles){if(player.x<o.x+o.w&&player.x+player.w>o.x&&player.y<o.y+o.h&&player.y+player.h>o.y){gameOver=true; const final=Math.floor(distance/10); if(final>best){best=final; localStorage.setItem('dash-runner-best',best); bestEl.textContent=best;}}}}
function drawPlayer(){ctx.fillStyle='#3557d6';ctx.fillRect(player.x,player.y,player.w,player.h); ctx.fillStyle='#fff';ctx.fillRect(player.x+16,player.y+8,6,6); ctx.fillStyle='#d96c06';ctx.fillRect(player.x+4,player.y+34,8,4); ctx.fillRect(player.x+18,player.y+34,8,4);}
function draw(){ ctx.fillStyle='#cdeeff'; ctx.fillRect(0,0,canvas.width,canvas.height); ctx.fillStyle='#fff'; ctx.fillRect(80,55,70,18); ctx.fillRect(320,80,85,18); ctx.fillRect(540,45,60,16); ctx.fillStyle='#98cf6f'; ctx.fillRect(0,286,canvas.width,74); ctx.fillStyle='#7ab255'; ctx.fillRect(0,300,canvas.width,60); ctx.fillStyle='#6c4f3d'; ctx.fillRect(0,286,canvas.width,8); drawPlayer(); obstacles.forEach(o=>{ctx.fillStyle='#8d5524';ctx.fillRect(o.x,o.y,o.w,o.h); ctx.fillStyle='#4f8f32';ctx.fillRect(o.x-3,o.y,o.w+6,8);}); if(gameOver){ctx.fillStyle='rgba(255,249,232,.94)';ctx.fillRect(220,115,280,110);ctx.strokeStyle='#2f2a24';ctx.lineWidth=4;ctx.strokeRect(220,115,280,110);ctx.fillStyle='#2c2a26';ctx.textAlign='center';ctx.font='bold 24px monospace';ctx.fillText('RUN OVER',360,155);ctx.font='16px monospace';ctx.fillText('Press Space or Restart',360,184);}}
function loop(){update();draw();requestAnimationFrame(loop)}
window.addEventListener('keydown',e=>{if([' ','ArrowUp','w'].includes(e.key)){e.preventDefault(); jump();}}); canvas.addEventListener('pointerdown',jump); restartBtn.onclick=reset; reset(); loop();
